---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-csi-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: Immediate
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  csi.storage.k8s.io/fstype: ext4
  type: gp2
  encrypted: "true"
  kmsKeyId: "a7db9c5d-a73d-43a1-84d1-fab0eaebf9f7"