---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-csi-test-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-csi-sc      # explicitly set the SC
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
    - name: app
      image: centos
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
      volumeMounts:
        - name: vol
          mountPath: /data
  volumes:
    - name: vol
      persistentVolumeClaim:
        claimName: ebs-csi-test-claim

