---
# Service account which is NOT integrated with IAM
apiVersion: v1
kind: ServiceAccount
metadata:
  name: non-sa-app

---
# Pod which sleeps for 24 hours. Container image has the AWS CLI installed
apiVersion: v1
kind: Pod
metadata:
  name: non-sa-app
spec:
  containers:
    - name: non-sa-app
      image: 904806826062.dkr.ecr.eu-west-1.amazonaws.com/aws-cli:0.1
      command: ["/bin/bash"]
      args: ["-c", "sleep 86400"]
  serviceAccountName: non-sa-app      # No IAM role mappings via trust policy


