# Uses a service account with no RBAC permissions, although mapped to an IAM role
# No permissions are inherited from the EC2 instance profile
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
spec:
  selector:
    matchLabels:
      app: ubuntu
  replicas: 1
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
        - name: ubuntu
          image: ubuntu
          command: ["sleep", "3600"]
          ports:
            - containerPort: 80
      serviceAccountName: ubuntu-sa

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ubuntu-sa
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::904806826062:role/mike-eks-service-acccount-role"
